[Feat-82] add hardware monitoring
taecontrol/larvis pull request #83
Opened 2023-12-11 14:04 UTC by AlexisTAE

close #82

2023-12-11 14:14 UTC, AlexisTAE commented
@rpereira-tae  i got the problem that in local the tests pass but here dont I dont know why?

2023-12-11 14:24 UTC, rpereira-tae requested changes

2023-12-11 14:24 UTC, rpereira-tae commented on src/Commands/CheckHardwareHealthCommand.php
> +    protected $description = 'check Cpu Memory and Disk space';
Update the description message to:

Checks CPU load, RAM usage and Disk space

2023-12-11 14:24 UTC, rpereira-tae commented on src/Services/HardwareService.php
> +        return $hardwareData;
Replace into:

```php
return new HardwareData($cpuLoad, $memory, $disk);
```

2023-12-11 14:35 UTC, rpereira-tae commented
The exception:

```bash
PHPUnit 9.5.27 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.2-1ubuntu2.14
Configuration: /home/runner/work/larvis/larvis/phpunit.xml

F..........................................                       43 / 43 (100%)

Time: 00:00.571, Memory: 30.00 MB

There was 1 failure:

1) Taecontrol\Larvis\Tests\Feature\Commands\CheckHardwareHealthTest::it_asserts_that_data_its_send_correctly
An expected request was not recorded.
Failed asserting that false is true.

/home/runner/work/larvis/larvis/vendor/laravel/framework/src/Illuminate/Http/Client/Factory.php:292
/home/runner/work/larvis/larvis/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:338
/home/runner/work/larvis/larvis/tests/Feature/Commands/CheckHardwareHealthTest.php:[6](https://github.com/taecontrol/larvis/actions/runs/7168684184/job/19517402656?pr=83#step:6:7)5

FAILURES!
Tests: 43, Assertions: [20](https://github.com/taecontrol/larvis/actions/runs/7168684184/job/19517402656?pr=83#step:6:21)1, Failures: 1.
Script vendor/bin/phpunit handling the test event returned with error code 1
Error: Process completed with exit code 1.
```

Happens when the `Http::assertSent` is false (the callback returns false or the url doesn't match):

```php
Http::assertSent(function (Request $request) use ($data) {
            $requestMemory = $request['memory'];
            $requestCpuLoad = $request['cpuLoad'];
            $requestTotalDisk = $request['disk']['totalSpace'];
            $requestFreeDisk = $request['disk']['freeSpace'];

            return $requestCpuLoad == $data['cpuLoad'] &&
                   $requestMemory == $data['memory'] &&
                   $requestFreeDisk == $data['disk']['freeSpace'] &&
                   $requestTotalDisk == $data['disk']['totalSpace'];
        });
```

The GH action uses `composer run-script test` to run the tests. If you try to run the tests through composer that test fails for some reason.

2023-12-11 14:37 UTC, rpereira-tae requested changes

2023-12-11 14:37 UTC, rpereira-tae commented on tests/Feature/Commands/CheckHardwareHealthTest.php
> +        $command = app(CheckHardwareHealthCommand::class);
Add PHPDoc on $command:

```suggestion
        /** @var CheckHardwareHealthCommand */
        $command = app(CheckHardwareHealthCommand::class);
```

2023-12-11 15:47 UTC, rpereira-tae requested changes

2023-12-11 15:47 UTC, rpereira-tae commented on src/Commands/CheckHardwareHealthCommand.php
>      public function handle()
Add function return type.

2023-12-11 15:47 UTC, rpereira-tae commented on src/Services/HardwareService.php
Add function return types to: getHardwareData, getDiskUsage, getMemoryUsage and getCpuLoadUsage

2023-12-11 15:54 UTC, rpereira-tae requested changes

2023-12-11 15:54 UTC, rpereira-tae commented on src/Services/HardwareService.php
> +        }
Don't create boolean variables and then assign them number values

2023-12-11 15:54 UTC, rpereira-tae commented on src/Services/HardwareService.php
> +        }
You should wrap this code using a try/catch, in case there's an error it can return the exception. The same with getMemoryUsage and getCpuLoadUsage

2023-12-11 16:00 UTC, rpereira-tae requested changes

2023-12-11 16:00 UTC, rpereira-tae commented on src/Services/HardwareService.php
> +        return $HardwareData->toArray();
If this is the only place where you use the value object it can be removed from the source code.

2023-12-11 16:18 UTC, AlexisTAE commented
I run test with composer and vendor in local and pass but I dont know why not pass in GH @rpereira-tae

2023-12-12 12:55 UTC, rpereira-tae approved these changes

2023-12-12 12:55 UTC, merged